### ISSUE TITLE
Add post search feature

### ISSUE THREAD

**Issue by farhadmpr** [farhadmpr/flask-blog#1]
The user can search for posts.

**Comment by Ali-Xoerex** [comment]
Hello @farhadmpr , May I work on this ? 
If so , please assign me

**Comment by farhadmpr** [comment]
> Hello @farhadmpr , May I work on this ?
> If so , please assign me

Yes, of course. Please do it. Thank you.

**Comment by Ali-Xoerex** [comment]
I hope #5 solves the issue
